### PR TITLE
Some improvements

### PR DESCRIPTION
**Pull request by besser82**
As described in the commit messages.

### CODE REVIEW

**Comment by besser82** [comment]
Rebased on recent `origin/master` branch.

**Comment by besser82** [comment]
Added a commit to optionally install an unstripped binary.

**Comment by besser82** [comment]
Now the change about the {C,LD}FLAGS is less intrusive.

**Comment by besser82** [comment]
Yay!  Thank you!  =)  I'll write you an email later during today.

**Comment by besser82** [comment]
Well, gcc 4.7.x series (RHEL6) complains about the doubled `typedef`…

**Comment by PeterPawn** [comment]
OK, I'll stop now with immediate reactions ... looks like your changes aren't complete yet and it seems better to wait for your message.

**Comment by er13** [comment]
Just wanted to point out the following [Freetz patches](http://trac.freetz.org/browser/trunk/make/decrypt-fritzos-cfg/patches) to decoder's Makefile (those from 010 to 040).

**Comment by PeterPawn** [comment]
I wrote @besser82 an e-mail meanwhile and am awaiting the answer. I'll keep Freetz and the patches for "decrypt-fritzos-cfg" in mind (and I'll try to keep them as stable as possible) - it's one of the aspects I meant above in my comment.

**Comment by er13** [comment]
@[6ca3609](https://github.com/PeterPawn/decoder/pull/16/commits/6ca3609f1ca6ef0f4b9160378aa51d931743cd0a): by appending to (instead of prepending) user/system supplied flags one makes sure that some flags are never get overwritten. I.e. if the desired behavior is "the user is allowed to set some flags specific for his system/configuration but not those important for some package feature to properly work" then appending is the way to go.

**Comment by PeterPawn** [comment]
It was my own mistake, that I commented all changes together as "approved" - the GitHub GUI lead me to the wrong point, where I thought, the comment would apply only to a single commit (c5bc03e).

**Comment by PeterPawn** [comment]
I'm unable to reproduce eb28a71 with the (or better my) proposed settings for compiler warnings - here I need to know, which compiler version and which settings were used to produce a warning, if a "switch" statement "falls through its cases".

c5bc03e will be applied with other changes.

Instead of b7daa99 I'd prefer an additional make target 'install-nostrip' - imho it's easier to use than one more variable (tab completion, etc.).

The other changes to 'Makefile' (6ca3609 is the 2nd version of the proposal) need more explanation and discussion (as mentioned in my e-mail).

**Comment by PeterPawn** [comment]
No e-mail from @besser82 was received yet (even if it was announced) and there was no answer on my own e-mail, too.

To bring this request to a conclusion, I've added my own changes meanwhile to fix those parts, where I can see a reason to do anything.

The changes to CFLAGS and LDFLAGS settings would do the opposite of my own intention. I want to overrule any predefined settings in these variables in a manner, that after merging, my own preferred settings (at least for the specified options) will be used.

Using ```override CFLAGS += ...``` is equivalent to ```override CFLAGS := $(CFLAGS) ...```, while the proposed changes would reverse this order.

So I'll close this PR here ... don't hesitate to start a discussion, if you think, I should overthink it again.

**Pull request closed without merging**
